# this add-on is no-longer powered by the bloated trash that is splunk Add-on builder
[install]
build = 1789410847
install_source_checksum = d2584562324ffabe676bff891704742905264d2e

[launcher]
author = Chris Younger
version = 1.4.6
description = Simple versioning for Splunk

[ui]
is_visible = 1
label = Git for Splunk

[package]
id = git_for_splunk
