[checkoverwrite-command]
syntax = [checkoverwrite]
shortdesc = [checks to see if any local overwrites exist]
usage = public

[removeoverwrite-command]
syntax = [removeoverwrite]
shortdesc = [removes any local overwrites]
usage = public
