[/opt/splunk/var/log/splunk/supervisor.log_Thu_Oct__1_16:52:06_2026_1189453431]
L-//_::_:___ = 0.045635
L-//_::_L7(L7)_ = 0.035714
L-//_::_L7(L7)_/ = 0.068452
L-//_::_L7(L7)__ = 0.134921
L-//_::__... = 0.035714
L-//_::__:-_ = 0.058532
L-//_::___ = 0.043651
L-//_::_____ = 0.069444
L-//_::_t__- = 0.117063
L-//_::_t___ = 0.080357
L-{\\"\\":\\"\\",\\"\\": = 0.171627
_source = /opt/splunk/var/log/splunk/supervisor.log
_sourcetype = supervisor-2
