[install]
is_configured = true
state = enabled
allows_disable = false

[ui]
is_visible = true
show_in_nav = true
label = Audit Trail

[launcher]
author = Splunk
description = App for Audit Trail dashboards
version = 1.0.0
