[capability::upgrade_splunk_shc]
[capability::upgrade_splunk_idxc]

[role_admin]
upgrade_splunk_shc = enabled
upgrade_splunk_idxc = enabled

[role_splunk_system_upgrader]
upgrade_splunk_shc = enabled
upgrade_splunk_idxc = enabled
list_search_head_clustering = enabled
list_indexer_cluster = enabled
edit_indexer_cluster = enabled
list_settings = enabled
use_remote_proxy = enabled
