[shcupgrade]
enforceTypes = true
field.id = number
field.status = string
field.from_version = string
field.to_version = string

[idxcurrent]
enforceTypes = true
field.id = number
field.upgrader_pid = number
field.status = string
field.from_version = string
field.to_version = string
field.timestamp = number

[idxpeers]
enforceTypes = true
field.id = number
field.orchestrator_pid = number
field.upgrade_id = number
field.from_version = string
field.to_version = string
field.overall_status = string
