[expose:upgrade_shc]
pattern = upgrade/shc/upgrade
methods = POST
allowRemoteProxy = true

[expose:upgrade_shc_member]
pattern = upgrade/shc/member_upgrade_internal
methods = POST
allowRemoteProxy = true

[expose:upgrade_shc_status]
pattern = upgrade/shc/status
methods = GET

[expose:upgrade_shc_recovery]
pattern = upgrade/shc/recovery
methods = POST

[expose:upgrade_cluster_instance]
pattern = upgrade/cluster/instance
methods = POST
allowRemoteProxy = true

[expose:upgrade_cluster_all_peers]
pattern = upgrade/cluster/all_peers
methods = POST

[expose:upgrade_cluster_standalone]
pattern = upgrade/standalone
methods = POST

[expose:upgrade_cluster_manager]
pattern = upgrade/cluster/manager
methods = POST

[expose:upgrade_cluster_status]
pattern = upgrade/cluster/status
methods = GET

[expose:upgrade_cluster_recovery]
pattern = upgrade/cluster/recovery
methods = POST

