[expose:tlPackage-agent-management-all-endpoints]
methods = GET,POST,DELETE,PATCH
pattern = /agent-management

[expose:tlPackage-agent-management-all-endpoints-webport-1]
methods = GET,POST,DELETE,PATCH
pattern = /agent-management/*

[expose:tlPackage-agent-management-all-endpoints-webport-2]
methods = GET,POST,DELETE,PATCH
pattern = /agent-management/*/*

[expose:tlPackage-agent-management-all-endpoints-webport-3]
methods = GET,POST,DELETE,PATCH
pattern = /agent-management/*/*/*

[expose:tlPackage-agent-management-all-endpoints-webport-4]
methods = GET,POST,DELETE,PATCH
pattern = /agent-management/*/*/*/*

[expose:tlPackage-agent-management-all-endpoints-webport-5]
methods = GET,POST,DELETE,PATCH
pattern = /agent-management/*/*/*/*/*

[expose:tlPackage-scimGroup]
methods = GET
pattern = /identity/provisioning/v1/scim/v2/Groups/*

[expose:tlPackage-scimGroups]
methods = GET
pattern = /identity/provisioning/v1/scim/v2/Groups

[expose:tlPackage-scimUser]
methods = GET,PUT,PATCH,DELETE
pattern = /identity/provisioning/v1/scim/v2/Users/*

[expose:tlPackage-scimUsers]
methods = GET
pattern = /identity/provisioning/v1/scim/v2/Users
