[install]
is_configured = 1
state = enabled
install_source_checksum = f2299ef2a5e9f602a9a6a419f03c4767cbd3cb90

[launcher]
author = local
description = Atomic inventory and change tracking for effective Splunk configuration.
version = 2.0.0

[ui]
is_visible = 1
label = Btool Config Inventory

[package]
id = TA_btool_config_inventory
