[gitforsplunk://test]
btool_conf_files = inputs, indexes, fields, props, limits, outputs, props, transforms, savedsearches, macros
include_btool_output = 1
index = _internal
interval = 300
remote_push = 1
repository_directory = /opt/splunk_git_repo/.git
split_savedsearches_conf = 0
working_directory = /opt/splunk/etc
